export const products = [
    {
      id: "1",
      name: "فستان سهرة فاخر",
      price: 1500,
      discount: 10,
      category: "فستان",
      rarity: "Luxe",
      image: "/image123.png",
    },
    {
      id: "2",
      name: "جيبة كلاسيك نادرة",
      price: 800,
      oldPrice: 750,
      discount: 0,
      category: "جيبة",
      rarity: "Rare",
      image: "/image123.png",
    },
    {
        id: "1",
        name: "فستان سهرة فاخر",
        price: 1500,
        discount: 10,
        category: "فستان",
        rarity: "Luxe",
        image: "/image123.png",
      },
      {
        id: "2",
        name: "جيبة كلاسيك نادرة",
        price: 800,
        oldPrice: 750,
        discount: 0,
        category: "جيبة",
        rarity: "Rare",
        image: "/image123.png",
      },    {
        id: "1",
        name: "فستان سهرة فاخر",
        price: 1500,
        discount: 10,
        category: "فستان",
        rarity: "Luxe",
        image: "/image123.png",
      },
      {
        id: "2",
        name: "جيبة كلاسيك نادرة",
        price: 800,
        oldPrice: 750,
        discount: 0,
        category: "جيبة",
        rarity: "Rare",
        image: "/image123.png",
      },    {
        id: "1",
        name: "فستان سهرة فاخر",
        price: 1500,
        discount: 10,
        category: "فستان",
        rarity: "Luxe",
        image: "/image123.png",
      },
      {
        id: "2",
        name: "جيبة كلاسيك نادرة",
        price: 800,
        oldPrice: 750,
        discount: 0,
        category: "جيبة",
        rarity: "Rare",
        image: "/image123.png",
      },    {
        id: "1",
        name: "فستان سهرة فاخر",
        price: 1500,
        discount: 10,
        category: "فستان",
        rarity: "Luxe",
        image: "/image123.png",
      },
      {
        id: "2",
        name: "جيبة كلاسيك نادرة",
        price: 800,
        oldPrice: 750,
        discount: 0,
        category: "جيبة",
        rarity: "Rare",
        image: "/image123.png",
      },    {
        id: "1",
        name: "فستان سهرة فاخر",
        price: 1500,
        discount: 10,
        category: "فستان",
        rarity: "Luxe",
        image: "/image123.png",
      },
      {
        id: "2",
        name: "جيبة كلاسيك نادرة",
        price: 800,
        oldPrice: 750,
        discount: 0,
        category: "جيبة",
        rarity: "Rare",
        image: "/image123.png",
      },    {
        id: "1",
        name: "فستان سهرة فاخر",
        price: 1500,
        discount: 10,
        category: "فستان",
        rarity: "Luxe",
        image: "/image123.png",
      },
      {
        id: "2",
        name: "جيبة كلاسيك نادرة",
        price: 800,
        oldPrice: 750,
        discount: 0,
        category: "جيبة",
        rarity: "Rare",
        image: "/image123.png",
      },    {
        id: "1",
        name: "فستان سهرة فاخر",
        price: 1500,
        discount: 10,
        category: "فستان",
        rarity: "Luxe",
        image: "/image123.png",
      },
      {
        id: "2",
        name: "جيبة كلاسيك نادرة",
        price: 800,
        oldPrice: 750,
        discount: 0,
        category: "جيبة",
        rarity: "Rare",
        image: "/image123.png",
      },
    // أضف المزيد حسب الحاجة
  ];
  